hm_1
Ruslan0056/golang-one pull request #1
Opened 2021-11-21 20:44 UTC by Ruslan0056

2021-11-22 06:01 UTC, v-lozhkin requested changes

2021-11-22 06:01 UTC, v-lozhkin commented on hm_1/main.go
> +
Все отлично, только нужно отформатировать код с помощью go fmt

2021-11-25 10:44 UTC, v-lozhkin approved these changes
Все супер

2021-11-25 10:45 UTC, Ruslan0056 commented on hm_1/main.go
> +
Код отформатирован

2021-11-30 20:51 UTC, merged