Dz 2
Ruslan0056/golang-one pull request #2
Opened 2021-11-25 10:37 UTC by Ruslan0056

2021-11-25 10:56 UTC, v-lozhkin requested changes

2021-11-25 10:56 UTC, v-lozhkin commented on hm_2/main.go
> +		var pi = math.Pi
Зачем класть константу из пакета в переменную? Можно использовать ее напрямую

2021-11-25 10:56 UTC, v-lozhkin commented on hm_2/main.go
> +		fmt.Scan(&S)
Зачем считывать дважды?

2021-11-25 10:56 UTC, v-lozhkin commented on hm_2/main.go
> +		var p = d / pi
Знак перепутали. Тут должно быть умножение

2021-11-25 10:56 UTC, v-lozhkin commented on hm_2/main.go
> +		var sotni = chislo / 100
Задание не совсем про это. Пример, как должно быть:
Введите число   123
Количество сотен =  1
Количество десятков =  2
Количество единиц =  3

2021-11-25 10:56 UTC, v-lozhkin commented on hm_2/main.go
> +			if bl == false {
bl - уже bool. Нет нужды сравнивать его с false. Достаточно написать 
if !bl {
...
}

2021-11-25 10:56 UTC, v-lozhkin commented on hm_2/main.go
> +			bl = false
Имя переменной должно нести ее смысл. 
Лучше назвать ее как-то notPrime

2021-11-25 19:37 UTC, Ruslan0056 commented on hm_2/main.go
> +		var sotni = chislo / 100
Все замечания учтены

2021-11-28 14:40 UTC, v-lozhkin approved these changes
Все ок

2021-12-01 20:45 UTC, merged