Dz 3
Ruslan0056/golang-one pull request #3
Opened 2021-11-28 21:01 UTC by Ruslan0056

2021-11-30 06:57 UTC, v-lozhkin requested changes

2021-11-30 06:57 UTC, v-lozhkin commented on hm_1/main.go
> +package main
Почему не мержите предыдущих два реквеста? В обоих стоит апрув (1 и 2 домашки)

2021-11-30 06:57 UTC, v-lozhkin commented on hm_3/main.go
> +		if b == 0 {
Программа свалится раньше, чем дойдет до этой проверки

2021-11-30 06:57 UTC, v-lozhkin commented on hm_3/main.go
> +		var i float32
В пакете math есть функция Pow для возведения в степень

2021-11-30 06:57 UTC, v-lozhkin commented on hm_3/main.go
> +		var j float32 = 1
Почему не использовать классический for с итератором?

2021-11-30 20:49 UTC, Ruslan0056 commented on hm_3/main.go
> +		if b == 0 {
правки внесены

2021-11-30 20:55 UTC, Ruslan0056 commented on hm_1/main.go
> +package main
Почему то не получается мержить 2 дз

2021-12-01 07:14 UTC, v-lozhkin commented on hm_3/main.go
> +		var j float64
Зачем его объявлять отдельно? Просто прямо в итераторе for j := 1; j < a; j++ {

2021-12-01 21:17 UTC, Ruslan0056 commented on hm_3/main.go
> +		var j float64
float с int не хочет сравнивать, получается либо как в новой версии прописывать в сравнении и операции float64 (j), либо объявлять отдельно.
если задать в самом начале a и b int, то при операции возведении в степень нужно прописывать, что a и b - float64.
получается, либо я не разобрался и что-то упустил, либо в любом случае прописывать повторно тип переменной

2021-12-02 18:44 UTC, v-lozhkin commented on hm_3/main.go
> +		var j float64
Можно это было сделать как 
```go
for j := float64(1); j < a; j++ {
			result *= j
		}
```

Но как сейчас тоже норм, принято

2021-12-02 18:44 UTC, v-lozhkin approved these changes

2021-12-06 16:54 UTC, merged